### PR TITLE
Revert a commit in ipxe that breaks Mellanox NICs

### PR DESCRIPTION
**Pull request by nshalman**
## Description

This would update iPXE to the latest master plus a revert of a commit identified to break Mellanox NICs.
This is a temporary measure that might need to be repeated on future updates of iPXE until ipxe/ipxe#1091 has been fixed correctly.

## Why is this needed

Relates to: #115, ipxe/ipxe#1091

## How Has This Been Tested?

I did repeated testing of iPXE binaries from my branches
[mainline-ipxe](https://github.com/nshalman/ipxedust/tree/mainline-ipxe)
[test-revert](https://github.com/nshalman/ipxedust/tree/test-revert)
to confirm that the issue exists and is addressed by the revert.

## How are existing users impacted? What migration steps/scripts do we need?

This would unbreak users of certain Mellanox NICs (Definitely Mellanox CX4, possibly others too)

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Hey @nshalman , im not seeing commit `fbc3b4a104698658202c2a83217ca8722453bf49` in ipxe/ipxe. you have a link by chance to this commit?

**Comment by nshalman** [comment]
https://github.com/nshalman/ipxe/tree/fix-mellanox / https://github.com/nshalman/ipxe/commit/fbc3b4a104698658202c2a83217ca8722453bf49

Because of how github works, https://github.com/ipxe/ipxe/commit/fbc3b4a104698658202c2a83217ca8722453bf49 also resolves.

**Comment by jacobweinstock** [comment]
hmmm...im thoroughly confused here. That link https://github.com/ipxe/ipxe/commit/fbc3b4a104698658202c2a83217ca8722453bf49 shows me this message:

image

**Comment by jacobweinstock** [comment]
oh i think i see, maybe. This is just GitHub doing redirects for us. This is a commit from your fork. correct?

**Comment by nshalman** [comment]
> oh i think i see, maybe. This is just GitHub doing redirects for us. Ultimately, this is a commit from your fork. correct?

Correct.

**Comment by nshalman** [comment]
I could make it explicit that we're pulling from my fork temporarily, but the nice thing about doing it this way is that as soon as ipxe is bumped the workaround is no longer in place. We fail securely back to upstream ipxe rather than risking staying stuck pointing at a fork. The worst possible outcome of future updates is that issue #115 (which will still be open) reappears in ipxedust.

**Review by jacobweinstock — APPROVED** [review]

**Pull request merged**
