### PR TITLE
Update pin/tftp library version:

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

This version fixes numerous bugs, race conditions, and a file descriptor leak.

## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by nshalman — DISMISSED** [review]
LGTM

**Review by nshalman — APPROVED** [review]
Still LGTM. I'm assuming that was DCO or somesuch?

**Comment by jacobweinstock** [comment]
> Still LGTM. I'm assuming that was DCO or somesuch?

Branch was out of date with main. Thanks for the quick approval!

**Comment by jacobweinstock** [comment]
Hey @mmlb, mind checking this one out?

**Comment by mmlb** [comment]
will do

**Review by mmlb — APPROVED** [review]

**Pull request merged**
